version: "3.9"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/modules-enabled/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
